// Extracts only the Simple Icons used by data/catalog.ts and data/skills.ts, so the app never
// ships the full 3,000+ icon package. Writes:
//   public/brand-icons.svg  an SVG sprite, cached by the browser and kept out of the JS bundles
//   data/brand-meta.ts      titles, colors and the sprite version (tiny, used by <BrandIcon>)
//   data/brand-icons.ts     full path data, only for the icon library's copy/download features
import { createHash } from "node:crypto"
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath, pathToFileURL } from "node:url"
import { dirname, join } from "node:path"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const si = await import(pathToFileURL(join(root, "node_modules/simple-icons/index.mjs")).href)
const bySlug = new Map(Object.values(si).filter((i) => i?.slug).map((i) => [i.slug, i]))

const sources = ["data/catalog.ts", "data/skills.ts"].map((f) => readFileSync(join(root, f), "utf8")).join("\n")
const slugs = [...new Set([...sources.matchAll(/icon:\s*"([^"]+)"/g)].map((m) => m[1]))].sort()

const icons = {}
for (const slug of slugs) {
  const icon = bySlug.get(slug)
  if (!icon) {
    console.warn(`! missing simple-icon: ${slug}`)
    continue
  }
  icons[slug] = { title: icon.title, hex: icon.hex, path: icon.path }
}

const out = `// Generated by scripts/generate-icons.mjs. Do not edit by hand.
// Brand icons from Simple Icons (https://simpleicons.org), CC0‑1.0.

export interface BrandIcon {
  title: string
  hex: string
  path: string
}

export const brandIcons: Record<string, BrandIcon> = ${JSON.stringify(icons, null, 2)}
`
writeFileSync(join(root, "data/brand-icons.ts"), out)

const sprite = `<svg xmlns="http://www.w3.org/2000/svg">${Object.entries(icons)
  .map(([slug, icon]) => `<symbol id="${slug}" viewBox="0 0 24 24"><path d="${icon.path}"/></symbol>`)
  .join("")}</svg>`
writeFileSync(join(root, "public/brand-icons.svg"), sprite)
const version = createHash("sha256").update(sprite).digest("hex").slice(0, 10)

const meta = Object.fromEntries(Object.entries(icons).map(([slug, { title, hex }]) => [slug, { title, hex }]))
writeFileSync(
  join(root, "data/brand-meta.ts"),
  `// Generated by scripts/generate-icons.mjs. Do not edit by hand.

/** Sprite URL with a content hash, so browsers re‑fetch it only when icons change. */
export const brandSprite = "/brand-icons.svg?v=${version}"

export const brandMeta: Record<string, { title: string; hex: string }> = ${JSON.stringify(meta)}
`,
)
console.log(`Wrote ${Object.keys(icons).length} icons (sprite ${(sprite.length / 1024).toFixed(0)} KB, v=${version})`)
