// Extracts only the brand icons CodeStack uses, so the app never ships the full 3,000+ icon
// Simple Icons package. Icons come from data/catalog.ts and data/skills.ts, plus the custom
// marks and Icons-page extras in scripts/icon-sources.mjs. Writes:
//   public/brand-icons.svg        sprite for every icon used across the site, cached by the browser
//   public/brand-icons-extra.svg  sprite for the Icons-page-only extras, loaded only there
//   data/brand-meta.ts            titles, colors and sprite versions (tiny, used by <BrandIcon>)
//   data/brand-icons.ts           full path data, only for the icon library's copy/download features
import { createHash } from "node:crypto"
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath, pathToFileURL } from "node:url"
import { dirname, join } from "node:path"
import { customIcons, extraSlugs } from "./icon-sources.mjs"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const si = await import(pathToFileURL(join(root, "node_modules/simple-icons/index.mjs")).href)
const bySlug = new Map(
  Object.values(si)
    .filter((i) => i?.slug)
    .map((i) => [i.slug, i]),
)

const lookup = (slug) => {
  const custom = customIcons[slug]
  if (custom) return custom
  const icon = bySlug.get(slug)
  if (icon) return { title: icon.title, hex: icon.hex, path: icon.path }
  console.warn(`! missing icon: ${slug}`)
}

const sources = ["data/catalog.ts", "data/skills.ts"].map((f) => readFileSync(join(root, f), "utf8")).join("\n")
const siteSlugs = new Set([...sources.matchAll(/icon:\s*"([^"]+)"/g)].map((m) => m[1]))
const extras = new Set([...Object.keys(customIcons), ...extraSlugs].filter((s) => !siteSlugs.has(s)))

const collect = (slugs) => Object.fromEntries([...slugs].sort().flatMap((slug) => ((icon) => (icon ? [[slug, icon]] : []))(lookup(slug))))
const siteIcons = collect(siteSlugs)
const extraIcons = collect(extras)
const icons = Object.fromEntries(Object.entries({ ...siteIcons, ...extraIcons }).sort(([a], [b]) => a.localeCompare(b)))

writeFileSync(
  join(root, "data/brand-icons.ts"),
  `// Generated by scripts/generate-icons.mjs. Do not edit by hand.
// Brand icons from Simple Icons (https://simpleicons.org, CC0‑1.0), plus the custom marks
// listed in scripts/icon-sources.mjs with their licenses.

export interface BrandIcon {
  title: string
  hex: string
  path: string
  /** Set when the path is not drawn on the default 24×24 grid. */
  viewBox?: string
  /** Icon set and license, for marks that do not come from Simple Icons. */
  source?: string
}

export const brandIcons: Record<string, BrandIcon> = ${JSON.stringify(icons, null, 2)}
`,
)

const writeSprite = (file, set) => {
  const sprite = `<svg xmlns="http://www.w3.org/2000/svg">${Object.entries(set)
    .map(([slug, icon]) => `<symbol id="${slug}" viewBox="${icon.viewBox ?? "0 0 24 24"}"><path d="${icon.path}"/></symbol>`)
    .join("")}</svg>`
  writeFileSync(join(root, "public", file), sprite)
  console.log(`${file}: ${Object.keys(set).length} icons, ${(sprite.length / 1024).toFixed(0)} KB`)
  return createHash("sha256").update(sprite).digest("hex").slice(0, 10)
}
const version = writeSprite("brand-icons.svg", siteIcons)
const extraVersion = writeSprite("brand-icons-extra.svg", extraIcons)

const meta = Object.fromEntries(
  Object.entries(icons).map(([slug, { title, hex, source }]) => [
    slug,
    { title, hex, ...(slug in extraIcons && { x: 1 }), ...(source && { source }) },
  ]),
)
writeFileSync(
  join(root, "data/brand-meta.ts"),
  `// Generated by scripts/generate-icons.mjs. Do not edit by hand.

/** Sprite URLs with a content hash, so browsers re‑fetch them only when icons change. */
export const brandSprite = "/brand-icons.svg?v=${version}"
/** Icons-page-only extras (\`x: 1\` below), kept out of the sprite every other page loads. */
export const brandSpriteExtra = "/brand-icons-extra.svg?v=${extraVersion}"

export const brandMeta: Record<string, { title: string; hex: string; x?: 1; source?: string }> = ${JSON.stringify(meta)}
`,
)
